name: Electron Build

on:
  push:
    branches:
      - main
jobs:
  buildwin:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run:
        cd src && npm install && npm run buildwin
    - name: Upload File
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: dist/*exe
  buildmac:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run:
        cd src && npm install && npm run buildmac
    - name: Upload File
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: dist/*dmg
