name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.19.0' # 指定所需的 Node.js 版本
          name: windows
          path: dist/*exe

      - name: Install dependencies
        run: yarn install # 或者您可以使用 npm install

      - name: Run build
        run: yarn run buildwin # 或者您可以使用 npm test